// ============================================================
// LUXORA — Orders Database Functions
// ============================================================

import { supabase } from '../supabase';
import type {
    CartItemWithProduct,
    Order,
    OrderItem,
    ShippingAddress,
} from '../types/database.types';

// ─────────────────────────────────────────────
// READ
// ─────────────────────────────────────────────

export async function getUserOrders(userId: string): Promise<Order[]> {
  const { data, error } = await supabase
    .from('orders')
    .select('*, order_items(*)')
    .eq('user_id', userId)
    .order('created_at', { ascending: false });

  if (error) {
    console.error('[DB] getUserOrders error:', error.message);
    throw new Error(error.message);
  }

  return (data as Order[]) ?? [];
}

export async function getOrderById(orderId: string): Promise<Order | null> {
  const { data, error } = await supabase
    .from('orders')
    .select('*, order_items(*)')
    .eq('id', orderId)
    .single();

  if (error) {
    if (error.code === 'PGRST116') return null;
    throw new Error(error.message);
  }

  return data as Order;
}

// ─────────────────────────────────────────────
// PLACE ORDER
// ─────────────────────────────────────────────

export interface PlaceOrderParams {
  userId: string;
  cartItems: CartItemWithProduct[];
  shippingAddress: ShippingAddress;
  paymentMethod: string;
}

export async function placeOrder(params: PlaceOrderParams): Promise<Order> {
  const { userId, cartItems, shippingAddress, paymentMethod } = params;

  if (cartItems.length === 0) {
    throw new Error('Cart is empty');
  }

  // Calculate total
  const totalAmount = cartItems.reduce((sum, item) => {
    return sum + item.products.price * item.quantity;
  }, 0);

  // Create order (order_number auto-generated by trigger)
  const { data: order, error: orderError } = await supabase
    .from('orders')
    .insert({
      user_id: userId,
      order_number: 'TEMP', // will be replaced by trigger
      total_amount: totalAmount,
      currency: 'USD',
      shipping_address: shippingAddress,
      payment_method: paymentMethod,
      payment_status: 'unpaid',
      status: 'pending',
    })
    .select()
    .single();

  if (orderError) {
    console.error('[DB] placeOrder (create order) error:', orderError.message);
    throw new Error(orderError.message);
  }

  // Create order items (snapshot of products at order time)
  const orderItems: Omit<OrderItem, 'id' | 'created_at'>[] = cartItems.map((item) => ({
    order_id: order.id,
    product_id: item.product_id,
    product_name: item.products.name,
    product_brand: item.products.brand ?? null,
    product_price: item.products.price,
    quantity: item.quantity,
    subtotal: item.products.price * item.quantity,
  }));

  const { error: itemsError } = await supabase.from('order_items').insert(orderItems);

  if (itemsError) {
    console.error('[DB] placeOrder (insert items) error:', itemsError.message);
    // Rollback: delete the order
    await supabase.from('orders').delete().eq('id', order.id);
    throw new Error(itemsError.message);
  }

  // Clear cart after successful order
  await supabase.from('cart_items').delete().eq('user_id', userId);

  return order as Order;
}